import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { FIRM, loadFirmBrandingPublic } from '../lib/firmBranding'

function localDateStr(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseMins(t){if(!t)return null;const m=t.match(/(\d+):(\d+)\s*(AM|PM)/i);if(m){let h=+m[1];const min=+m[2],ap=m[3].toUpperCase();if(ap==='PM'&&h!==12)h+=12;if(ap==='AM'&&h===12)h=0;return h*60+min}return null}
function calcHours(a,b){const x=parseMins(a),y=parseMins(b);if(x==null||y==null)return 0;let d=y-x;if(d<=0)d+=1440;return +(d/60).toFixed(2)}
const card={background:'#0f172a',border:'1px solid #1e293b',borderRadius:16,padding:20}
const input={width:'100%',boxSizing:'border-box',background:'#07111f',border:'1px solid #334155',borderRadius:9,color:'#fff',padding:'11px 12px'}

export default function ClockIn(){
 const params=new URLSearchParams(window.location.search),tenantHint=params.get('t')||''
 const[firmName,setFirmName]=useState(FIRM.name||'Time Clock'),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[pin,setPin]=useState(''),[showPin,setShowPin]=useState(false),[action,setAction]=useState('toggle'),[authToken,setAuthToken]=useState(null),[openEntry,setOpenEntry]=useState(null),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false),[now,setNow]=useState(new Date()),[req,setReq]=useState({type:'pto',start:'',end:'',reason:''})
 useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[])
 useEffect(()=>{loadFirmBrandingPublic(tenantHint||undefined).then(f=>{if(f?.name)setFirmName(f.name)}).catch(()=>{});load()},[])
 async function load(){setLoading(true);const{data,error}=await supabase.rpc('kiosk_load_secure',{p_tenant:tenantHint||null});if(error)setMsg(error.message);setEmployees(data?.employees||[]);setLoading(false)}
 function begin(emp,nextAction){if(!emp.has_pin){setMsg(`${emp.name} does not have a kiosk PIN yet. Contact a manager.`);return}setSelected(emp);setAction(nextAction);setPin('');setShowPin(false);setAuthToken(null);setOpenEntry(null);setMsg('')}
 async function authenticate(){if(!selected||!pin.trim())return;setSaving(true);const{data,error}=await supabase.rpc('kiosk_login',{p_employee_id:selected.id,p_pin:pin.trim(),p_tenant:tenantHint||null});if(error||!data?.token){setSaving(false);setMsg(error?.message||'Could not verify PIN.');return}setAuthToken(data.token);if(action==='toggle'){const{data:open}=await supabase.rpc('emp_open_entry',{p_token:data.token});setOpenEntry(open||null)}setSaving(false)}
 async function doToggle(){if(!authToken)return;setSaving(true);const stamp=new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',hour12:true});let error;if(openEntry){const h=calcHours(openEntry.inTime,stamp);({error}=await supabase.rpc('emp_clock_out',{p_token:authToken,p_entry_id:openEntry.id,p_out_time:stamp,p_hours:h}));if(!error)setMsg(`✅ ${selected.name} clocked out at ${stamp} — ${h.toFixed(2)}h logged.`)}else{({error}=await supabase.rpc('emp_clock_in',{p_token:authToken,p_date:localDateStr(),p_in_time:stamp}));if(!error)setMsg(`✅ ${selected.name} clocked in at ${stamp}.`)}if(error)setMsg('❌ '+error.message);setSaving(false);setSelected(null);setAuthToken(null)}
 async function submitTimeOff(){if(!authToken||!req.start||!req.end)return;const s=new Date(req.start+'T00:00:00'),e=new Date(req.end+'T00:00:00');if(e<s){setMsg('End date must be after start date.');return}const days=Math.round((e-s)/86400000)+1;setSaving(true);const{error}=await supabase.rpc('emp_timeoff_submit',{p_token:authToken,p_type:req.type,p_start_date:req.start,p_end_date:req.end,p_days:days,p_reason:req.reason||null});if(error){setSaving(false);setMsg('❌ '+error.message);return}await supabase.functions.invoke('send-email',{body:{kind:'employee_timeoff_notification',employee_portal_token:authToken,request_type:req.type,start_date:req.start,end_date:req.end,days}}).catch(()=>{});setSaving(false);setMsg(`✅ ${selected.name}'s time-off request was submitted for approval.`);setSelected(null);setAuthToken(null);setReq({type:'pto',start:'',end:'',reason:''})}
 const filtered=employees.filter(e=>e.name?.toLowerCase().includes(search.toLowerCase()))
 return <div style={{minHeight:'100vh',background:'linear-gradient(160deg,#071c30,#0a3f60)',padding:24,fontFamily:'system-ui',color:'#fff'}}><div style={{maxWidth:720,margin:'0 auto'}}>
   <div style={{textAlign:'center',marginBottom:18}}><div style={{fontSize:12,fontWeight:800,color:'#60a5fa',letterSpacing:'.12em',textTransform:'uppercase'}}>{firmName}</div><div style={{fontSize:34,fontWeight:800}}>{now.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</div><div style={{fontSize:12,color:'#94a3b8'}}>{now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</div></div>
   {msg&&<div style={{...card,marginBottom:14,color:msg.startsWith('❌')?'#f87171':'#86efac'}}>{msg}</div>}
   <div style={card}><div style={{fontWeight:800,fontSize:18,textAlign:'center'}}>Employee Time Clock</div><div style={{fontSize:12,color:'#94a3b8',textAlign:'center',margin:'5px 0 15px'}}>Tap your name, then enter your private PIN.</div><input style={{...input,marginBottom:14}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your name..."/>
   {loading?<div style={{padding:32,textAlign:'center',color:'#64748b'}}>Loading…</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:10}}>{filtered.map(emp=><div key={emp.id} style={{background:'#0a1628',border:'1px solid #1e3a5f',borderRadius:12,padding:14}}><div style={{fontWeight:800}}>{emp.name}</div><div style={{fontSize:11,color:'#64748b',minHeight:18}}>{emp.title||''}</div><button onClick={()=>begin(emp,'toggle')} style={{width:'100%',marginTop:10,padding:9,border:0,borderRadius:8,background:'#2563eb',color:'#fff',fontWeight:700,cursor:'pointer'}}>Clock In / Out</button><button onClick={()=>begin(emp,'timeoff')} style={{width:'100%',marginTop:7,padding:8,border:'1px solid #334155',borderRadius:8,background:'transparent',color:'#93c5fd',fontWeight:700,cursor:'pointer'}}>🌴 Request Time Off</button></div>)}</div>}
   </div>
   {selected&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.72)',display:'flex',alignItems:'center',justifyContent:'center',padding:20,zIndex:1000}} onClick={e=>e.target===e.currentTarget&&setSelected(null)}><div style={{...card,width:'100%',maxWidth:420}}><div style={{fontSize:17,fontWeight:800,marginBottom:4}}>{selected.name}</div>{!authToken?<><div style={{fontSize:12,color:'#94a3b8',marginBottom:12}}>Enter your Employee Portal PIN to continue.</div><div style={{position:'relative'}}><input autoFocus type={showPin?'text':'password'} inputMode="numeric" style={{...input,paddingRight:46}} value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>e.key==='Enter'&&authenticate()} placeholder="PIN"/><button type="button" onClick={()=>setShowPin(v=>!v)} aria-label={showPin?'Hide PIN':'Show PIN'} aria-pressed={showPin} style={{position:'absolute',right:7,top:'50%',transform:'translateY(-50%)',width:34,height:34,border:0,borderRadius:8,background:'transparent',color:'#94a3b8',cursor:'pointer'}}><span aria-hidden="true">{showPin?'◉':'◎'}</span></button></div><button disabled={saving||!pin.trim()} onClick={authenticate} style={{width:'100%',marginTop:10,padding:11,border:0,borderRadius:8,background:'#2563eb',color:'#fff',fontWeight:800}}>{saving?'Checking…':'Continue'}</button></>:action==='toggle'?<><div style={{fontSize:13,color:'#cbd5e1',margin:'12px 0'}}>{openEntry?`Currently clocked in since ${openEntry.inTime}.`:'Currently clocked out.'}</div><button disabled={saving} onClick={doToggle} style={{width:'100%',padding:12,border:0,borderRadius:8,background:openEntry?'#dc2626':'#16a34a',color:'#fff',fontWeight:800}}>{saving?'Saving…':openEntry?'Clock Out':'Clock In'}</button></>:<><div style={{display:'grid',gap:9,marginTop:12}}><select style={input} value={req.type} onChange={e=>setReq(r=>({...r,type:e.target.value}))}><option value="pto">PTO</option><option value="sick">Sick</option><option value="vacation">Vacation</option></select><input style={input} type="date" value={req.start} onChange={e=>setReq(r=>({...r,start:e.target.value}))}/><input style={input} type="date" value={req.end} onChange={e=>setReq(r=>({...r,end:e.target.value}))}/><textarea style={input} rows={3} value={req.reason} onChange={e=>setReq(r=>({...r,reason:e.target.value}))} placeholder="Reason (optional)"/></div><button disabled={saving||!req.start||!req.end} onClick={submitTimeOff} style={{width:'100%',marginTop:10,padding:11,border:0,borderRadius:8,background:'#2563eb',color:'#fff',fontWeight:800}}>{saving?'Submitting…':'Submit Request'}</button></>}<button onClick={()=>setSelected(null)} style={{width:'100%',marginTop:8,padding:8,border:0,background:'transparent',color:'#94a3b8'}}>Cancel</button></div></div>}
 </div></div>
}