import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const HELD=10
const xml=(s:string,status=200)=>new Response(`<?xml version="1.0" encoding="UTF-8"?><Response>${s}</Response>`,{status,headers:{'Content-Type':'text/xml'}})
function businessHours(d:Date){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'numeric',hour12:false}).formatToParts(d),wd=p.find(x=>x.type==='weekday')?.value,h=Number(p.find(x=>x.type==='hour')?.value||0);return !['Sat','Sun'].includes(String(wd))&&h>=9&&h<18}
async function verifySW(secret:string,url:string,params:Record<string,string>,sig:string){if(!secret||!sig)return false;let s=url;for(const k of Object.keys(params).sort())s+=k+(params[k]??'');const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']),raw=await crypto.subtle.sign('HMAC',key,enc.encode(s)),expected=btoa(String.fromCharCode(...new Uint8Array(raw)));if(expected.length!==sig.length)return false;let d=0;for(let i=0;i<expected.length;i++)d|=expected.charCodeAt(i)^sig.charCodeAt(i);return d===0}
serve(async req=>{if(req.method!=='POST')return xml('',405);const raw=await req.text(),p=new URLSearchParams(raw);const swSecret=Deno.env.get('SW_SIGNING_SECRET')??'',sig=req.headers.get('x-signalwire-signature')??'';if(swSecret){const params:Record<string,string>={};for(const[k,v]of p)params[k]=v;if(!await verifySW(swSecret,req.url,params,sig))return xml('<Hangup/>',403)}else console.warn('[receive-call] SW_SIGNING_SECRET absent; structural callback validation only');const callSid=p.get('CallSid')||'',from=p.get('From')||'',to=p.get('To')||'';if(!callSid||!from||!to)return xml('',400);try{
const db0=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),to10pre=to.replace(/\D/g,'').slice(-10);
const {data:romySettings}=await db0.from('settings').select('sw_inbound_did').eq('tenant_id','a0000000-0000-0000-0000-000000000001').limit(1).maybeSingle();
const romy10=String(romySettings?.sw_inbound_did||'').replace(/\D/g,'').slice(-10);
if(romy10&&to10pre===romy10){
  const handoff=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/romylabs-receive-call`,{
    method:'POST',
    headers:{'Content-Type':'application/x-www-form-urlencoded','x-romylabs-internal':Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''},
    body:raw
  });
  return new Response(await handoff.text(),{status:handoff.status,headers:{'Content-Type':'text/xml'}});
}const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),to10=to.replace(/\D/g,'').slice(-10);if(to10.length!==10)return xml('',400);const {data:rows,error}=await db.from('settings').select('name,call_forward_number,sw_inbound_did,sw_outbound_did,tenant_id').not('tenant_id','is',null);if(error)throw error;const matches=(rows||[]).filter((r:any)=>[r.sw_inbound_did,r.sw_outbound_did].some(v=>String(v||'').replace(/\D/g,'').slice(-10)===to10));if(matches.length!==1){console.error('[receive-call] DID not uniquely mapped',{to10,matches:matches.length});return xml('<Hangup/>',403)}const s:any=matches[0],tenantId=s.tenant_id,from10=from.replace(/\D/g,'').slice(-10),inbound10=String(s.sw_inbound_did||'').replace(/\D/g,'').slice(-10),outbound10=String(s.sw_outbound_did||'').replace(/\D/g,'').slice(-10),isOwned=(n:string)=>n===inbound10||n===outbound10,isAgent=isOwned(from10)&&isOwned(to10);if(isAgent){const cutoff=new Date(Date.now()-HELD*60000).toISOString();const {data:held}=await db.from('incoming_calls').select('conference_name,callsid').eq('tenant_id',tenantId).in('status',['ringing','answered']).gte('created_at',cutoff).not('conference_name','is',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(held?.conference_name){await db.from('incoming_calls').update({status:'answered'}).eq('tenant_id',tenantId).eq('callsid',held.callsid).eq('status','ringing');return xml(`<Dial><Conference endConferenceOnExit="false">${held.conference_name}</Conference></Dial>`)}const {data:out}=await db.from('outbound_calls').select('id,conference_name').eq('tenant_id',tenantId).in('status',['pending','connected','ringing','answered']).not('conference_name','is',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(out?.conference_name){await db.from('outbound_calls').update({status:'connected'}).eq('tenant_id',tenantId).eq('id',out.id).eq('status','pending');return xml(`<Dial><Conference endConferenceOnExit="false">${out.conference_name}</Conference></Dial>`)}return xml('<Hangup/>')}
const safeName=String(s.name||'our office').replace(/[<>&"]/g,''),base=`${Deno.env.get('SUPABASE_URL')}/functions/v1`,voicemail=`${Deno.env.get('SUPABASE_URL')}/functions/v1/voicemail-recorded`;
const isDirectLocal=to10===outbound10&&outbound10.length===10;
if(isDirectLocal){
  const conf=`direct-${callSid.replace(/[^A-Za-z0-9_-]/g,'').slice(0,100)}`;
  const {error:ins}=await db.from('incoming_calls').insert({callsid:callSid,conference_name:conf,from_number:from.slice(0,32),department:'Direct Callback',status:'ringing',tenant_id:tenantId});
  if(ins&&ins.code!=='23505')throw ins;
  return xml(`<Dial><Conference startConferenceOnEnter="true" endConferenceOnExit="false" waitUrl="${base}/hold-music" waitMethod="GET" statusCallback="${base}/caller-hangup?conf=${encodeURIComponent(conf)}" statusCallbackEvent="leave end" statusCallbackMethod="POST" record="record-from-start" recordingStatusCallback="${base}/call-recorded?conf=${encodeURIComponent(conf)}&tenant=${encodeURIComponent(tenantId)}&callsid=${encodeURIComponent(callSid)}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}">${conf}</Conference></Dial>`);
}if(s.call_forward_number){const f=String(s.call_forward_number).replace(/[^+0-9]/g,'');return xml(`<Dial timeout="25"><Number>${f}</Number></Dial><Say voice="Polly.Ruth-Neural" language="en-US"><speak>Thank you for calling ${safeName}. We're sorry we missed you. Please leave your name, number, and a brief message and we'll get back to you shortly.</speak></Say><Record action="${voicemail}" maxLength="120" playBeep="true"/>`)}if(!businessHours(new Date()))return xml(`<Say voice="Polly.Ruth-Neural" language="en-US"><speak>Thank you for calling ${safeName}. Our office is currently closed. We're available Monday through Friday, nine AM to six PM Eastern. Please leave us a message after the tone and we'll return your call the next business day.</speak></Say><Record action="${voicemail}" maxLength="120" playBeep="true"/>`);const ivr=`${Deno.env.get('SUPABASE_URL')}/functions/v1/ivr-route`,g=`<speak>Thank you for calling ${safeName}. <break time="400ms"/> If you're an existing client, check your email or text messages for your secure client portal link. <break time="600ms"/> Press <say-as interpret-as="digits">1</say-as> to dial by extension. <break time="300ms"/> Press <say-as interpret-as="digits">2</say-as> to speak with a tax advisor. <break time="300ms"/> Press <say-as interpret-as="digits">3</say-as> to speak with a tax associate. <break time="300ms"/> Or press <say-as interpret-as="digits">0</say-as> for the operator.</speak>`;return xml(`<Gather numDigits="1" timeout="8" action="${ivr}" method="POST"><Say voice="Polly.Ruth-Neural" language="en-US">${g}</Say></Gather><Redirect method="POST">${ivr}</Redirect>`)}catch(e){console.error('[receive-call]',e);return xml(`<Say>We're sorry, we're experiencing a brief technical issue. Please try your call again in just a moment.</Say>`,500)}})
