-- Enforce one signed document per client e-sign attachment.
-- Completion evidence is embedded on non-POA PDFs; IRS/state POAs remain unstamped.
-- Standalone certificate PDFs are no longer filed by esign_finalize.

create or replace function public.esign_finalize(
  p_id text,
  p_client_name text,
  p_doc_type text,
  p_signed_by text,
  p_signer_ip text,
  p_signed_at timestamptz,
  p_saved_doc_type text,
  p_cert_url text default null,
  p_attachments jsonb default '[]'::jsonb,
  p_cert_size bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  r public.esigns%rowtype;
  att jsonb;
  safe_attachments jsonb:='[]'::jsonb;
  result jsonb;
  project_storage_prefix constant text:='https://mpxgxfqdbquzkrvvejkh.supabase.co/storage/v1/object/sign/documents/';
  completion_note text;
begin
  if p_id !~ '^es_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    raise exception 'Signing request not found.';
  end if;

  select * into r from public.esigns where id=p_id limit 1;
  if r.id is null then raise exception 'Signing request not found.'; end if;
  if coalesce(r.status,'')<>'Signed' then raise exception 'Signing request is not signed.'; end if;

  p_client_name:=r.client_name;
  p_doc_type:=r.doc_type;
  p_signed_by:=coalesce(r.signer_full_name,r.signed_name,p_signed_by);
  p_signer_ip:=coalesce(r.signer_ip,p_signer_ip);
  p_signed_at:=coalesce(r.signed_at,r.signed_timestamp,p_signed_at,now());
  p_saved_doc_type:=case
    when r.doc_type in ('Service Addendum','Fee Agreement Addendum') then 'Agreements'
    else 'E-Signatures'
  end;

  -- Intentionally ignore p_cert_url/p_cert_size. Completion evidence belongs
  -- on the signed PDF itself; it is not a separate client document.
  if jsonb_typeof(coalesce(p_attachments,'[]'::jsonb))='array' then
    for att in select * from jsonb_array_elements(coalesce(p_attachments,'[]'::jsonb)) loop
      if coalesce(att->>'url','') like project_storage_prefix||'%' then
        safe_attachments:=safe_attachments||jsonb_build_array(att);
      end if;
    end loop;
  end if;

  result:=public._esign_finalize_internal(
    p_id,p_client_name,p_doc_type,p_signed_by,p_signer_ip,p_signed_at,
    p_saved_doc_type,null,safe_attachments,null
  );

  -- Correct legacy attachment notes generated by the internal finalize helper.
  -- We keep the internal helper stable because it also owns lead/task/workflow
  -- advancement, but certificate-document creation is disabled above.
  for att in select * from jsonb_array_elements(safe_attachments) loop
    completion_note:=case
      when lower(coalesce(att->>'completionStamped','false'))='true'
        then E'\n✅ E-signature completion details embedded on signed document'
      else E'\nPOA signed — completion stamp intentionally not applied'
    end;

    update public.documents
    set notes=
      replace(
        coalesce(notes,''),
        E'\n✅ Certificate of completion appended',
        ''
      ) || completion_note
    where tenant_id=r.tenant_id
      and client=p_client_name
      and file_url=att->>'url';
  end loop;

  return result;
end
$function$;

revoke all on function public.esign_finalize(
  text,text,text,text,text,timestamptz,text,text,jsonb,bigint
) from public,anon;

grant execute on function public.esign_finalize(
  text,text,text,text,text,timestamptz,text,text,jsonb,bigint
) to anon,authenticated,service_role;
